# Generated by Django 5.2.7 on 2025-10-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sports_type',
            field=models.CharField(default='General'),
        ),
    ]
