# Generated by Django 5.2.7 on 2025-10-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='actor',
            field=models.CharField(max_length=150),
        ),
    ]
