# Generated by Django 5.2.7 on 2025-10-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_alter_actionlog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
